/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * A value a statement can hold, going out.
 *
 * INT64 is `bigint` and FLOAT is `number`, which is the one rule worth
 * learning before anything else here: a JavaScript number stops being
 * exact at 2^53 and zu's integers go to 2^63, so a count that came back
 * as a number would be a count you cannot trust.
 */
export type ZuValue =
  | null
  | boolean
  | number
  | bigint
  | string
  | ZuNode
  | ZuRel
  | ZuPath
  | ZuDate
  | ZuTime
  | ZuTimestamp
  | ZuDuration
  | ZuValue[]
  | { [field: string]: ZuValue }

/**
 * A value a statement can be given, coming in.
 *
 * Wider than what comes out, because a `number` that is whole binds as
 * INT64 and `undefined` binds as null, which is what makes an optional
 * field of a plain object pass straight through.
 */
export type ZuParam =
  | null
  | undefined
  | boolean
  | number
  | bigint
  | string
  | ZuDate
  | ZuTime
  | ZuTimestamp
  | ZuDuration
  | ZuParam[]
  | { [field: string]: ZuParam }

/**
 * A walk through the graph: nodes and edges, alternating, a node at
 * each end.
 *
 * The two lists are kept apart rather than interleaved, because the
 * question a caller asks is almost always about one of them. A path of
 * one node has no edges and is the shortest there is.
 */
export interface ZuPath {
  readonly nodes: ZuNode[]
  readonly rels: ZuRel[]
}

/**
 * Something the engine wants to say about a statement that ran anyway.
 *
 * A notice is a completion condition of its own, so it carries a
 * GQLSTATUS the same way a failure does. The one raised today is
 * `01G11`, which says an aggregate ignored a null.
 */
export interface ZuNotice {
  readonly code: string
  readonly condition: string
  readonly message: string
  readonly docUrl: string
}

/**
 * The rows a statement gave back.
 *
 * An array, so iterating it is `for (const row of rows)` and nothing
 * else. What a wrapper object would have carried is carried as
 * properties beside the elements: `columns` for the projection in the
 * order it was written, `gqlstatus` for the condition the statement
 * completed with, and `notices` for what it wanted to say on the way.
 */
export interface ZuRows<Row = Record<string, ZuValue>> extends Array<Row> {
  readonly columns: string[]
  readonly gqlstatus: string
  readonly notices: ZuNotice[]
}

/**
 * One batch of a streamed result.
 *
 * The rows of a whole result with the same array trick and one fewer
 * property: `columns` is the statement's projection and is the same on
 * every batch of one stream, and what a statement completed with is not
 * known until it has, so it is on the summary rather than here.
 */
export interface ZuBatch<Row = Record<string, ZuValue>> extends Array<Row> {
  readonly columns: string[]
}

/**
 * What a streamed statement did, known once it has ended.
 *
 * The rows are gone by then, which is the point of streaming, so this
 * is what is worth keeping about a result nobody held: what it
 * projected, how much of it was read, whether the reader stopped it
 * early, and what the engine wanted to say along the way.
 */
export interface ZuSummary {
  readonly columns: string[]
  /** How many rows were handed over, which is fewer than the statement
   * would have returned when the reader stopped early. */
  readonly rows: number
  readonly stopped: boolean
  /**
   * Whether the rows arrived as they were made, rather than the
   * statement running whole and being handed over in batches
   * afterwards. A statement that has to see every row before it can
   * give one, which is `ORDER BY`, `DISTINCT`, the aggregates and
   * anything that writes, is the second kind, and so is a plan the
   * pipeline executor does not take. The loop over it reads the same
   * either way, so this is here for a caller measuring where the time
   * went rather than for one deciding what to do next.
   */
  readonly streamed: boolean
  readonly notices: ZuNotice[]
}

/**
 * What a streamed statement takes beside its parameters.
 */
export interface ZuStreamOptions extends ZuStatementOptions {
  /**
   * How many rows a batch may hold. The engine's own vector by
   * default, which is the unit it already works in and the one that
   * costs nothing to hand over. Name a size when the rows are going
   * somewhere with a size of its own, an Arrow record batch or an
   * HTTP chunk.
   *
   * A ceiling and not a promise: batches are cut out of rows that have
   * already been made, so the last piece of a run of them is whatever
   * was left, and a size above the engine's vector gets the vector. It
   * is what bounds how much a reader holds at once, which is the
   * question a caller is asking when they name one.
   */
  readonly batchRows?: number
}

/**
 * What a statement takes beside its parameters.
 *
 * An object rather than a bare signal, because the options that follow
 * it belong in the same place and a third argument that changes meaning
 * is one nobody can read at a call site.
 */
export interface ZuStatementOptions {
  /**
   * Stops the statement when it fires, through the same interrupt a
   * shell answers `Ctrl-C` with: the executor notices at the boundary it
   * was already stopping at, the statement ends, and the connection is
   * exactly as it was. The promise rejects with whatever the signal
   * gives as its reason, which is what `fetch` does, so
   * `AbortSignal.timeout(50)` rejects with a `TimeoutError` and
   * `controller.abort(new MyError())` rejects with `MyError`.
   *
   * A signal that has already fired stops the statement before the
   * engine sees it at all.
   */
  readonly signal?: AbortSignal
}

/**
 * What a failed call throws.
 *
 * An ordinary `Error`, so every `catch`, logger and unhandled rejection
 * handler already knows what to do with it. What makes it a zu error is
 * the fields, and none of them has to be parsed back out of the
 * message: `code` picks the branch, `line` and `column` underline the
 * token, `retryable` decides whether a retry loop goes round again.
 */
export interface ZuError extends Error {
  /**
   * The condition's class, written out: `ZuSyntaxError`,
   * `ZuDataError`, `ZuTransactionError`, `ZuConnectionError`,
   * `ZuInterrupted`, `ZuUsageError`, `ZuInternalError`, or `ZuError`
   * for a condition in a class none of those name.
   */
  readonly name: string
  /** Whether running the same statement again could succeed. */
  readonly retryable: boolean
  /**
   * The GQLSTATUS, five characters. Absent on a mistake this client
   * caught before the engine saw it, which is why a caller mapping
   * codes to branches has to tell a missing one from an unknown one.
   */
  readonly code?: string
  /** The standard's own words for that code. */
  readonly condition?: string
  readonly severity?: 'success' | 'noData' | 'warning' | 'informational' | 'exception'
  readonly docUrl?: string
  /** Where in the statement, for a condition that happened somewhere. */
  readonly line?: number
  readonly column?: number
  readonly offset?: number
  /** The whole line `column` indexes into, for underlining it. */
  readonly excerpt?: string
}
/**
 * One connection to one database.
 *
 * Statements run on it in order, one at a time. It reads the database
 * as of when it was opened, which is why a program that wants to see
 * another writer's work takes a new connection rather than waiting on
 * this one.
 */
export declare class Connection {
  /** Where the database this is connected to lives. */
  get path(): string
  /** Whether this connection refuses every statement that writes. */
  get readOnly(): boolean
  /** Whether the connection is still open. */
  get open(): boolean
  /**
   * Runs one statement and gives back its rows.
   *
   * The parameters are named, never positional, because zuQL names
   * them: `$id` in the statement is `id` in the object. A name the
   * statement does not use is an error from the engine rather than a
   * value quietly ignored.
   */
  query<Row = Record<string, ZuValue>>(statement: string, params?: Record<string, ZuParam> | null, options?: ZuStatementOptions | null): Promise<ZuRows<Row>>
  /**
   * Runs one statement for its effect and gives back nothing.
   *
   * The same call as [`Connection::query`] with the rows dropped,
   * which is what a schema statement or a write wants: a result nobody
   * reads still costs a row object per row on the way out.
   */
  exec(statement: string, params?: Record<string, ZuParam> | null, options?: ZuStatementOptions | null): Promise<void>
  /**
   * Runs one statement and gives back a cursor over its rows.
   *
   * The pull underneath `stream`, which is what a program uses. The
   * statement does not start here: it starts on the first read, so
   * that a cursor made and not read is not a scan holding the
   * connection against every statement after it.
   */
  cursor(statement: string, params?: Record<string, ZuParam> | null, options?: ZuStreamOptions | null): ZuCursor
  /**
   * Closes the connection and releases the database.
   *
   * Closing twice does nothing the second time, which is what makes
   * `await using` safe to combine with an explicit close in a branch
   * that ran first.
   */
  close(): void
  /**
   * The disposal `await using` calls, which is the intended way to
   * scope a connection. `close` stays public for callers who cannot
   * use it.
   *
   * It is also reachable as `Symbol.asyncDispose`, which is what
   * `await using` actually looks for and which [`wire_disposal`] puts
   * on every connection as it is made.
   */
  dispose(): Promise<void>
}

/**
 * One statement, read a batch at a time.
 *
 * This is the pull underneath the stream and not the shape a program
 * should be reaching for: `conn.stream(...)` gives back something that
 * is async-iterable, turns into the web's own `ReadableStream`, and
 * stops itself when the loop over it breaks.
 */
export declare class ZuCursor {
  /**
   * The next batch of rows, or `null` once the statement has ended.
   *
   * An array of row objects with the column names beside it, which
   * is the value `query` gives for a whole result and for the same
   * reason: what a caller does with rows is iterate them.
   */
  next(): Promise<ZuBatch | null>
  /**
   * Stops the statement and waits for it to let go of the
   * connection.
   *
   * Waits, because a stream abandoned while the next statement on
   * the same connection is already being asked for would make that
   * statement queue behind a scan nobody is reading. Stopping is not
   * a failure: the rows already handed over stand, and the summary
   * says the statement was stopped.
   */
  cancel(): Promise<void>
  /**
   * What the statement did, once it has ended, and `null` until
   * then.
   *
   * The column names are here as well as beside every batch, because
   * a statement that gave back no rows gave back no batches either
   * and its projection is still worth knowing.
   */
  get summary(): ZuSummary | null
}

/**
 * A date, as days from 1970-01-01.
 *
 * A count rather than a set of fields, which is what the engine
 * stores and what makes two dates compare as two numbers. `Temporal`
 * reached Stage 4 in March 2026 but is unflagged only in Node 26 and
 * the newest browsers, and Node 24 is still the active LTS, so this
 * is the stable type and the runtimes that have `Temporal` reach it
 * through the opt-in rather than through a type that changes shape
 * under them.
 */
export declare class ZuDate {
  days: number
  constructor(days: number)
  /**
   * The same thing as a plain object, for the reason [`ZuNode::to_json`]
   * gives.
   */
  toJSON(): object
}

/**
 * A duration, which is a count of months or a count of nanoseconds
 * and never both.
 *
 * The two kinds do not mix, because no number of days is a month: a
 * value holding both would have to invent an answer for one month
 * after 31 January, and the standard does not ask for the invention.
 * `kind` says which one this is, and the other count is zero.
 */
export declare class ZuDuration {
  /** A duration of `months` months, which is the year-month kind. */
  static ofMonths(months: bigint): ZuDuration
  /** A duration of `nanos` nanoseconds, which is the day-time kind. */
  static ofNanos(nanos: bigint): ZuDuration
  /** Which of the two kinds this is: `yearMonth` or `dayTime`. */
  get kind(): string
  /** The months, which is zero for a day-time duration. */
  get months(): bigint
  /** The nanoseconds, which is zero for a year-month duration. */
  get nanos(): bigint
  /**
   * The same thing as a plain object, for the reason [`ZuNode::to_json`]
   * gives.
   */
  toJSON(): object
}

/**
 * One node of the graph.
 *
 * The table is the name written in the schema and the offset is the
 * row it sits at in that table, which together are what identifies a
 * node in zu. The offset is a `bigint` for the reason every other
 * 64-bit integer here is one.
 *
 * The 64-bit fields are held as integers and handed out as `bigint` by
 * a getter, rather than being held as a `bigint` and handed out
 * directly, because a `bigint` is a JavaScript value and a value
 * cannot be held by a struct that is built on a threadpool thread
 * where there is no environment to build one in.
 */
export declare class ZuNode {
  get table(): string
  get offset(): bigint
  /**
   * The same thing as a plain object.
   *
   * Every field here is a getter on the prototype, which is what
   * lets a 64-bit field be handed out as a `bigint`, and a getter is
   * invisible to `JSON.stringify` and to a shallow copy. So each of
   * these classes says what it holds when it is asked, and a caller
   * stringifying a row gets the node rather than `{}`. A `bigint`
   * still has no JSON spelling, so a caller doing that passes a
   * replacer, which they already had to.
   */
  toJSON(): object
}

/**
 * One edge of the graph.
 *
 * `ord` is where the edge's properties sit, which is its place in the
 * order the table was loaded in. That is what names an edge: a pair of
 * endpoints does not, since the same pair may run more than once and
 * each of those edges carries its own values. It is the field a caller
 * usually ignores and the one nothing else can replace.
 */
export declare class ZuRel {
  get table(): string
  get src(): bigint
  get dst(): bigint
  get ord(): bigint
  /**
   * The same thing as a plain object, for the reason [`ZuNode::to_json`]
   * gives.
   */
  toJSON(): object
}

/**
 * A time of day, as nanoseconds from midnight, with the offset from
 * UTC in minutes for a zoned one and `null` for a local one.
 *
 * The offset is minutes and never an IANA name, which is the engine's
 * decision and worth repeating here: a name is a rule that changes
 * under a stored value when the zone database is updated, and a value
 * that means something different tomorrow is not a value.
 */
export declare class ZuTime {
  offset?: number
  constructor(nanos: bigint, offset?: number | undefined | null)
  get nanos(): bigint
  /**
   * The same thing as a plain object, for the reason [`ZuNode::to_json`]
   * gives.
   */
  toJSON(): object
}

/**
 * A date and a time together, as nanoseconds from the epoch, with the
 * offset from UTC in minutes for a zoned one and `null` for a local
 * one.
 *
 * A zoned one holds the instant in UTC and the offset separately, so
 * two of them compare as instants while each still prints in the zone
 * it was written in.
 */
export declare class ZuTimestamp {
  offset?: number
  constructor(nanos: bigint, offset?: number | undefined | null)
  get nanos(): bigint
  /**
   * The same thing as a plain object, for the reason [`ZuNode::to_json`]
   * gives.
   */
  toJSON(): object
}

/**
 * The revision of the C ABI this client implements the semantics of.
 *
 * Not the same number as [`version`] and not meant to be: the ABI is
 * the specification every zu client is graded against, so this is what
 * says which edition of that specification the behaviour here matches,
 * and it moves when the specification does rather than when this crate
 * does.
 */
export declare function abiVersion(): string

/**
 * Opens the database at `path` and connects to it.
 *
 * Creates one when the path holds nothing, which is what a first
 * program expects and what every embedded database does. A read-only
 * connection never creates anything.
 */
export declare function connect(path: string, options?: ConnectOptions | undefined | null): Promise<Connection>

/**
 * What a connection can be opened with.
 *
 * Every field is optional and every default is the engine's, because
 * a client that invents its own defaults is a client whose numbers
 * have to be found and changed twice.
 */
export interface ConnectOptions {
  /**
   * Opens without creating and refuses every statement that writes.
   * A read-only connection never creates a database, so a mistyped
   * path is an error here rather than an empty database.
   */
  readOnly?: boolean
  /** How much memory the executor may hold, in bytes. */
  memoryLimit?: bigint
  /** How many threads the executor may use. */
  threads?: number
}

/** The version of the client. */
export declare function version(): string
