/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * A value a statement can hold, going out.
 *
 * INT64 is `bigint` and FLOAT is `number`, which is the one rule worth
 * learning before anything else here: a JavaScript number stops being
 * exact at 2^53 and zu's integers go to 2^63, so a count that came back
 * as a number would be a count you cannot trust.
 */
export type ZuValue =
  | null
  | boolean
  | number
  | bigint
  | string
  | ZuNode
  | ZuRel
  | ZuPath
  | ZuDate
  | ZuTime
  | ZuTimestamp
  | ZuDuration
  | ZuValue[]
  | { [field: string]: ZuValue }

/**
 * A value a statement can be given, coming in.
 *
 * Wider than what comes out, because a `number` that is whole binds as
 * INT64 and `undefined` binds as null, which is what makes an optional
 * field of a plain object pass straight through.
 */
export type ZuParam =
  | null
  | undefined
  | boolean
  | number
  | bigint
  | string
  | ZuDate
  | ZuTime
  | ZuTimestamp
  | ZuDuration
  | ZuParam[]
  | { [field: string]: ZuParam }

/**
 * A walk through the graph: nodes and edges, alternating, a node at
 * each end.
 *
 * The two lists are kept apart rather than interleaved, because the
 * question a caller asks is almost always about one of them. A path of
 * one node has no edges and is the shortest there is.
 */
export interface ZuPath {
  readonly nodes: ZuNode[]
  readonly rels: ZuRel[]
}

/**
 * Something the engine wants to say about a statement that ran anyway.
 *
 * A notice is a completion condition of its own, so it carries a
 * GQLSTATUS the same way a failure does. The one raised today is
 * `01G11`, which says an aggregate ignored a null.
 */
export interface ZuNotice {
  readonly code: string
  readonly condition: string
  readonly message: string
  readonly docUrl: string
}

/**
 * The rows a statement gave back.
 *
 * An array, so iterating it is `for (const row of rows)` and nothing
 * else. What a wrapper object would have carried is carried as
 * properties beside the elements: `columns` for the projection in the
 * order it was written, `gqlstatus` for the condition the statement
 * completed with, and `notices` for what it wanted to say on the way.
 */
export interface ZuRows<Row = Record<string, ZuValue>> extends Array<Row> {
  readonly columns: string[]
  readonly gqlstatus: string
  readonly notices: ZuNotice[]
}

/**
 * One batch of a streamed result.
 *
 * The rows of a whole result with the same array trick and one fewer
 * property: `columns` is the statement's projection and is the same on
 * every batch of one stream, and what a statement completed with is not
 * known until it has, so it is on the summary rather than here.
 */
export interface ZuBatch<Row = Record<string, ZuValue>> extends Array<Row> {
  readonly columns: string[]
}

/**
 * What a streamed statement did, known once it has ended.
 *
 * The rows are gone by then, which is the point of streaming, so this
 * is what is worth keeping about a result nobody held: what it
 * projected, how much of it was read, whether the reader stopped it
 * early, and what the engine wanted to say along the way.
 */
export interface ZuSummary {
  readonly columns: string[]
  /** How many rows were handed over, which is fewer than the statement
   * would have returned when the reader stopped early. */
  readonly rows: number
  readonly stopped: boolean
  /**
   * Whether the rows arrived as they were made, rather than the
   * statement running whole and being handed over in batches
   * afterwards. A statement that has to see every row before it can
   * give one, which is `ORDER BY`, `DISTINCT`, the aggregates and
   * anything that writes, is the second kind, and so is a plan the
   * pipeline executor does not take. The loop over it reads the same
   * either way, so this is here for a caller measuring where the time
   * went rather than for one deciding what to do next.
   */
  readonly streamed: boolean
  readonly notices: ZuNotice[]
}

/**
 * What a streamed statement takes beside its parameters.
 */
export interface ZuStreamOptions extends ZuStatementOptions {
  /**
   * How many rows a batch may hold. The engine's own vector by
   * default, which is the unit it already works in and the one that
   * costs nothing to hand over. Name a size when the rows are going
   * somewhere with a size of its own, an Arrow record batch or an
   * HTTP chunk.
   *
   * A ceiling and not a promise: batches are cut out of rows that have
   * already been made, so the last piece of a run of them is whatever
   * was left, and a size above the engine's vector gets the vector. It
   * is what bounds how much a reader holds at once, which is the
   * question a caller is asking when they name one.
   */
  readonly batchRows?: number
}

/**
 * What a statement takes beside its parameters.
 *
 * An object rather than a bare signal, because the options that follow
 * it belong in the same place and a third argument that changes meaning
 * is one nobody can read at a call site.
 */
export interface ZuStatementOptions {
  /**
   * Stops the statement when it fires, through the same interrupt a
   * shell answers `Ctrl-C` with: the executor notices at the boundary it
   * was already stopping at, the statement ends, and the connection is
   * exactly as it was. The promise rejects with whatever the signal
   * gives as its reason, which is what `fetch` does, so
   * `AbortSignal.timeout(50)` rejects with a `TimeoutError` and
   * `controller.abort(new MyError())` rejects with `MyError`.
   *
   * A signal that has already fired stops the statement before the
   * engine sees it at all.
   */
  readonly signal?: AbortSignal
}

/**
 * What a failed call throws.
 *
 * An ordinary `Error`, so every `catch`, logger and unhandled rejection
 * handler already knows what to do with it. What makes it a zu error is
 * the fields, and none of them has to be parsed back out of the
 * message: `code` picks the branch, `line` and `column` underline the
 * token, `retryable` decides whether a retry loop goes round again.
 */
export interface ZuError extends Error {
  /**
   * The condition's class, written out: `ZuSyntaxError`,
   * `ZuDataError`, `ZuTransactionError`, `ZuConnectionError`,
   * `ZuInterrupted`, `ZuUsageError`, `ZuInternalError`, or `ZuError`
   * for a condition in a class none of those name.
   */
  readonly name: string
  /** Whether running the same statement again could succeed. */
  readonly retryable: boolean
  /**
   * The GQLSTATUS, five characters. Absent on a mistake this client
   * caught before the engine saw it, which is why a caller mapping
   * codes to branches has to tell a missing one from an unknown one.
   */
  readonly code?: string
  /** The standard's own words for that code. */
  readonly condition?: string
  readonly severity?: 'success' | 'noData' | 'warning' | 'informational' | 'exception'
  readonly docUrl?: string
  /** Where in the statement, for a condition that happened somewhere. */
  readonly line?: number
  readonly column?: number
  readonly offset?: number
  /** The whole line `column` indexes into, for underlining it. */
  readonly excerpt?: string
}
