/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * `Temporal.PlainDate`, on a program that has it.
 *
 * Asked of `globalThis` rather than imported, because `Temporal`
 * reached Stage 4 in March 2026 and which `lib` declares it is
 * different in every version of TypeScript that has shipped since. A
 * program compiling against a `lib` that has `Temporal` gets the real
 * type here and is checked against it. One compiling against a `lib`
 * that does not gets `unknown`, which needs a cast at the call site and
 * is the truth: this client cannot promise a type the compiler has
 * never heard of, and it should not fail to compile for saying so.
 */
export type ZuPlainDate = typeof globalThis extends {
  Temporal: { PlainDate: new (...args: any[]) => infer Value }
}
  ? Value
  : unknown

/** `Temporal.PlainTime`, on the terms [[ZuPlainDate]] gives. */
export type ZuPlainTime = typeof globalThis extends {
  Temporal: { PlainTime: new (...args: any[]) => infer Value }
}
  ? Value
  : unknown

/** `Temporal.PlainDateTime`, on the terms [[ZuPlainDate]] gives. */
export type ZuPlainDateTime = typeof globalThis extends {
  Temporal: { PlainDateTime: new (...args: any[]) => infer Value }
}
  ? Value
  : unknown

/** `Temporal.ZonedDateTime`, on the terms [[ZuPlainDate]] gives. */
export type ZuZonedDateTime = typeof globalThis extends {
  Temporal: { ZonedDateTime: new (...args: any[]) => infer Value }
}
  ? Value
  : unknown

/** `Temporal.Duration`, on the terms [[ZuPlainDate]] gives. Named for
 * the standard's class rather than for this client's `ZuDuration`,
 * which is the other one. */
export type ZuTemporalDuration = typeof globalThis extends {
  Temporal: { Duration: new (...args: any[]) => infer Value }
}
  ? Value
  : unknown

/**
 * Every `Temporal` value this client understands, and nothing at all on
 * a program whose `lib` has no `Temporal`.
 *
 * Nothing rather than `unknown` there, because this one is a member of
 * a union: `unknown` in a union swallows it and would turn every row
 * and every parameter into `unknown` for everybody. `never` in a union
 * vanishes, so a program without `Temporal` types sees exactly what it
 * saw before this existed.
 */
export type ZuTemporalValue = typeof globalThis extends {
  Temporal: { Instant: new (...args: any[]) => infer Instant }
}
  ? Instant | ZuPlainDate | ZuPlainTime | ZuPlainDateTime | ZuZonedDateTime | ZuTemporalDuration
  : never

/**
 * A value a statement can hold, going out.
 *
 * INT64 is `bigint` and FLOAT is `number`, which is the one rule worth
 * learning before anything else here: a JavaScript number stops being
 * exact at 2^53 and zu's integers go to 2^63, so a count that came back
 * as a number would be a count you cannot trust. `bigIntMode` changes
 * that for a statement or for a connection, with the hazard it
 * documents.
 *
 * A date, a time, a timestamp and a duration are the four classes by
 * default and `Temporal` values on a connection opened with
 * `{ temporal: true }`. A time with an offset is the exception in both
 * directions: `Temporal` has no type for one, so it stays a `ZuTime`.
 */
export type ZuValue =
  | null
  | boolean
  | number
  | bigint
  | string
  | ZuNode
  | ZuRel
  | ZuPath
  | ZuDate
  | ZuTime
  | ZuTimestamp
  | ZuDuration
  | ZuTemporalValue
  | ZuValue[]
  | { [field: string]: ZuValue }

/**
 * A value a statement can be given, coming in.
 *
 * Wider than what comes out, because a `number` that is whole binds as
 * INT64 and `undefined` binds as null, which is what makes an optional
 * field of a plain object pass straight through. A `Temporal` value
 * binds as the zu value it is on every connection, whether or not the
 * connection asked for `Temporal` on the way out, because recognizing
 * one costs a property read and refusing one would be a rule nobody
 * could guess.
 */
export type ZuParam =
  | null
  | undefined
  | boolean
  | number
  | bigint
  | string
  | ZuDate
  | ZuTime
  | ZuTimestamp
  | ZuDuration
  | ZuTemporalValue
  | ZuParam[]
  | { [field: string]: ZuParam }

/**
 * A value an appender takes, which is narrower than what a statement
 * takes.
 *
 * A column of an appender has one type, read from the table when the
 * appender opened, and every value in it is that type. So there is no
 * `null` here: a column that holds nulls cannot be appended to at all
 * and the appender says so when it opens, and `undefined` in a row is a
 * value the caller forgot rather than a null they meant. There are no
 * lists and no objects either, because a property column holds a scalar.
 *
 * BYTES is a `Uint8Array`, which is the one type here that no statement
 * parameter can be, and INT64 is a `bigint` or a whole `number` below
 * 2^53. A number past that is refused rather than rounded, because past
 * 2^53 a number no longer names one integer.
 */
export type ZuAppendValue =
  | boolean
  | number
  | bigint
  | string
  | Uint8Array
  | ZuDate
  | ZuTime
  | ZuTimestamp
  | ZuDuration
  | ZuTemporalValue

/**
 * One value of a registered frame's column, when the column is written
 * as a plain array.
 *
 * The same values an appender takes, without the bytes: a column of
 * BYTES is a column no statement can read back yet, so registering one
 * would be naming data the caller cannot get at. There is no `null`
 * either, for the reason there is none in a row of an appender.
 */
export type ZuFrameValue =
  | boolean
  | number
  | bigint
  | string
  | ZuDate
  | ZuTime
  | ZuTimestamp
  | ZuDuration
  | ZuTemporalValue

/**
 * One column of a registered frame.
 *
 * A typed array is the shape that costs nothing: the engine reads it
 * where it lies and no byte of it is copied. A plain array is read into
 * buffers of this client's own, because an array holds values of the
 * runtime rather than numbers, and its first value settles what the
 * column holds.
 */
export type ZuFrameColumn =
  | Int8Array
  | Uint8Array
  | Uint8ClampedArray
  | Int16Array
  | Uint16Array
  | Int32Array
  | Uint32Array
  | Float32Array
  | Float64Array
  | BigInt64Array
  | BigUint64Array
  | readonly ZuFrameValue[]

/**
 * An Arrow table or record batch, described by its shape rather than by
 * its class.
 *
 * Structural on purpose. `apache-arrow` is not a dependency of this
 * client and should not have to be: recognizing a table by the two
 * things every version of it has means a caller's copy of that library
 * and this client's are never two copies of one package disagreeing
 * about `instanceof`, and it means anything else that speaks the same
 * shape works too.
 */
export interface ZuArrowTable {
  readonly schema: { readonly fields: readonly { readonly name: string }[] }
  getChildAt(index: number): unknown
}

/**
 * Columns the caller already holds, ready to be registered under a name.
 *
 * An Arrow table, or an object of column name to values. Both are read
 * where they lie wherever there is one run of bytes to read: the two
 * cases that copy are an Arrow column that arrived in several chunks,
 * which is concatenated once, and a plain JavaScript array, which was
 * never a column of numbers to begin with.
 */
export type ZuFrame = ZuArrowTable | Record<string, ZuFrameColumn>

/**
 * An edge list, as the pairs of row numbers it is.
 *
 * Rows are numbered from zero in the order their columns were written,
 * because at load time a row has no other name. The flat spelling is
 * there for a program that built its edges in memory and would rather
 * not make a million two element arrays to hand them over: two elements
 * an edge, read in one pass.
 */
export type ZuEdges = readonly (readonly [number, number])[] | Int32Array | Uint32Array

/**
 * What a load writes, and how much of it.
 */
export interface ZuLoadOptions {
  /** The node table, which gets a row per element of every column. */
  readonly nodes: string
  /** The rel table holding the edges between those rows. `rel` by default. */
  readonly rels?: string
  /** The node table's properties, as column name to values. */
  readonly columns?: Readonly<Record<string, ZuFrameColumn>>
  /** The edges, as pairs of row numbers. */
  readonly edges?: ZuEdges | null
  /**
   * How many rows the node table has.
   *
   * Read off the columns when there are any, so this is for the load
   * that writes a graph with no properties at all, and a check on the
   * columns when both are given.
   */
  readonly rows?: number
}

/**
 * What went into a load.
 */
export interface ZuLoadStats {
  readonly nodes: number
  readonly rels: number
  readonly columns: number
}

/**
 * A walk through the graph: nodes and edges, alternating, a node at
 * each end.
 *
 * The two lists are kept apart rather than interleaved, because the
 * question a caller asks is almost always about one of them. A path of
 * one node has no edges and is the shortest there is.
 */
export interface ZuPath {
  readonly nodes: ZuNode[]
  readonly rels: ZuRel[]
}

/**
 * Something the engine wants to say about a statement that ran anyway.
 *
 * A notice is a completion condition of its own, so it carries a
 * GQLSTATUS the same way a failure does. The one raised today is
 * `01G11`, which says an aggregate ignored a null.
 */
export interface ZuNotice {
  readonly code: string
  readonly condition: string
  readonly message: string
  readonly docUrl: string
}

/**
 * What a column of a columnar read turned out to hold.
 *
 * Narrower than the type the statement declared, because the question
 * here is which buffer arrived: a time with an offset and a time
 * without are the same 64 bit cells, and the offset rides beside as
 * `zone`. `value` is the fallback for what no fixed width cell covers,
 * which is nodes, rels, paths, lists and records, and `null` is a
 * column that held nothing else.
 */
export type ZuColumnType =
  | 'null'
  | 'bool'
  | 'int'
  | 'float'
  | 'string'
  | 'date'
  | 'time'
  | 'datetime'
  | 'duration'
  | 'value'

/**
 * One column of a result, as the buffer holding it.
 *
 * Every field is present on every column and holds null where it does
 * not apply, so reading one is a switch on `type` rather than a series
 * of tests for what is there. Which field carries the values follows
 * from the type: `values` for everything of a fixed width, `data` and
 * `offsets` for strings, `items` for what no buffer covers, and none of
 * them for a column of nulls.
 *
 * The buffers are the engine's own, handed over rather than copied, and
 * they are laid out the way Arrow lays them out: values end to end, a
 * boolean as one bit a row, a string column as its bytes and `length +
 * 1` offsets into them, where row `i` spans `offsets[i]` to `offsets[i
 * + 1]`.
 */
export interface ZuColumn {
  readonly name: string
  readonly type: ZuColumnType
  readonly length: number
  /**
   * The cells, for a column of a fixed width: `BigInt64Array` for
   * integers, nanoseconds and months, `Float64Array` for floats,
   * `Int32Array` for days, and a `Uint8Array` of packed bits for
   * booleans, least significant bit first.
   */
  readonly values: BigInt64Array | Float64Array | Int32Array | Uint8Array | null
  /** The bytes of every string end to end, for a string column. */
  readonly data: Uint8Array | null
  /**
   * `length + 1` offsets into `data`, for a string column. Narrow until
   * the bytes pass what a 32 bit offset addresses, which is the
   * difference Arrow calls Utf8 against LargeUtf8.
   */
  readonly offsets: Int32Array | BigInt64Array | null
  /** The values themselves, for a column of type `value`. */
  readonly items: ZuValue[] | null
  /**
   * One bit a row, least significant bit first, set meaning the row has
   * a value. Null when every row has one, which is the common case and
   * the one where a reader gets to skip the test.
   */
  readonly validity: Uint8Array | null
  /** How many rows are null, which is zero when `validity` is null. */
  readonly nulls: number
  /** What one cell counts: `days`, `nanos` or `months`. */
  readonly unit: 'days' | 'nanos' | 'months' | null
  /** Minutes east of UTC, for a column of zoned times or datetimes. */
  readonly zone: number | null
}

/**
 * A whole result read down its columns.
 *
 * `rows` is every column's length, and is the answer for a statement
 * that projected nothing at all. `gqlstatus` and `notices` are the
 * statement's, exactly as they are on the rows.
 */
export interface ZuColumnar {
  readonly rows: number
  readonly columns: ZuColumn[]
  readonly gqlstatus: string
  readonly notices: ZuNotice[]
}

/**
 * The rows a statement gave back.
 *
 * An array, so iterating it is `for (const row of rows)` and nothing
 * else. What a wrapper object would have carried is carried as
 * properties beside the elements: `columns` for the projection in the
 * order it was written, `gqlstatus` for the condition the statement
 * completed with, and `notices` for what it wanted to say on the way.
 */
export interface ZuRows<Row = Record<string, ZuValue>> extends Array<Row> {
  readonly columns: string[]
  readonly gqlstatus: string
  readonly notices: ZuNotice[]
}

/**
 * One batch of a streamed result.
 *
 * The rows of a whole result with the same array trick and one fewer
 * property: `columns` is the statement's projection and is the same on
 * every batch of one stream, and what a statement completed with is not
 * known until it has, so it is on the summary rather than here.
 */
export interface ZuBatch<Row = Record<string, ZuValue>> extends Array<Row> {
  readonly columns: string[]
}

/**
 * What a streamed statement did, known once it has ended.
 *
 * The rows are gone by then, which is the point of streaming, so this
 * is what is worth keeping about a result nobody held: what it
 * projected, how much of it was read, whether the reader stopped it
 * early, and what the engine wanted to say along the way.
 */
export interface ZuSummary {
  readonly columns: string[]
  /** How many rows were handed over, which is fewer than the statement
   * would have returned when the reader stopped early. */
  readonly rows: number
  readonly stopped: boolean
  /**
   * Whether the rows arrived as they were made, rather than the
   * statement running whole and being handed over in batches
   * afterwards. A statement that has to see every row before it can
   * give one, which is `ORDER BY`, `DISTINCT`, the aggregates and
   * anything that writes, is the second kind, and so is a plan the
   * pipeline executor does not take. The loop over it reads the same
   * either way, so this is here for a caller measuring where the time
   * went rather than for one deciding what to do next.
   */
  readonly streamed: boolean
  readonly notices: ZuNotice[]
}

/**
 * What a streamed statement takes beside its parameters.
 */
export interface ZuStreamOptions extends ZuStatementOptions {
  /**
   * How many rows a batch may hold. The engine's own vector by
   * default, which is the unit it already works in and the one that
   * costs nothing to hand over. Name a size when the rows are going
   * somewhere with a size of its own, an Arrow record batch or an
   * HTTP chunk.
   *
   * A ceiling and not a promise: batches are cut out of rows that have
   * already been made, so the last piece of a run of them is whatever
   * was left, and a size above the engine's vector gets the vector. It
   * is what bounds how much a reader holds at once, which is the
   * question a caller is asking when they name one.
   */
  readonly batchRows?: number
}

/**
 * How INT64 is spelled on the way out.
 *
 * `bigint` is the default and is the only one of the two that is always
 * right, because zu's integers go to 2^63 and a JavaScript number stops
 * telling one integer from the next at 2^53.
 *
 * `number` is for the program that has already decided its integers are
 * small: ids that count in millions, a `count(*)` over a table that
 * will never be one, a row about to be handed to `JSON.stringify`,
 * which cannot serialize a `bigint` at all. It is worth knowing exactly
 * what is being traded for that. Which integers a database holds is a
 * property of the data and not of the program, so a query that returned
 * numbers for every row of a test database is a query that can meet a
 * larger one in production. This client refuses that row rather than
 * rounding it, with a `ZuUsageError` naming the column and the value,
 * so the failure is loud and local rather than an answer that is quietly
 * off by one. It is still a failure that arrives at read time, on a
 * machine that is not yours, which is why the default is the other one.
 *
 * The mode reaches the INT64 columns of a result and nothing else. A
 * node's `offset`, an edge's `src`, `dst` and `ord`, and the nanosecond
 * counts of the temporal classes stay `bigint` in both modes, because
 * they are properties of classes the addon registers once and not
 * values a statement can respell.
 */
export type ZuBigIntMode = 'bigint' | 'number'

/**
 * What a statement takes beside its parameters.
 *
 * An object rather than a bare signal, because the options that follow
 * it belong in the same place and a third argument that changes meaning
 * is one nobody can read at a call site.
 */
export interface ZuStatementOptions {
  /**
   * How INT64 comes back from this statement. `bigint` unless the
   * connection was opened with the other mode, and either way a
   * statement may name the one it wants.
   */
  readonly bigIntMode?: ZuBigIntMode
  /**
   * Stops the statement when it fires, through the same interrupt a
   * shell answers `Ctrl-C` with: the executor notices at the boundary it
   * was already stopping at, the statement ends, and the connection is
   * exactly as it was. The promise rejects with whatever the signal
   * gives as its reason, which is what `fetch` does, so
   * `AbortSignal.timeout(50)` rejects with a `TimeoutError` and
   * `controller.abort(new MyError())` rejects with `MyError`.
   *
   * A signal that has already fired stops the statement before the
   * engine sees it at all.
   */
  readonly signal?: AbortSignal
}

/**
 * What a transaction takes when it starts.
 */
export interface ZuTransactionOptions {
  /**
   * Starts it `READ ONLY`, which the engine refuses a write inside of
   * at the statement that writes rather than at this call.
   *
   * Worth asking for on a span that only reads, because saying so is
   * how a statement that was not meant to write is stopped by the
   * database rather than by review.
   */
  readonly readOnly?: boolean
}

/**
 * What a failed call throws.
 *
 * An ordinary `Error`, so every `catch`, logger and unhandled rejection
 * handler already knows what to do with it. What makes it a zu error is
 * the fields, and none of them has to be parsed back out of the
 * message: `code` picks the branch, `line` and `column` underline the
 * token, `retryable` decides whether a retry loop goes round again.
 */
export interface ZuError extends Error {
  /**
   * The condition's class, written out: `ZuSyntaxError`,
   * `ZuDataError`, `ZuTransactionError`, `ZuConnectionError`,
   * `ZuInterrupted`, `ZuUsageError`, `ZuInternalError`, or `ZuError`
   * for a condition in a class none of those name.
   */
  readonly name: string
  /** Whether running the same statement again could succeed. */
  readonly retryable: boolean
  /**
   * The GQLSTATUS, five characters. Absent on a mistake this client
   * caught before the engine saw it, which is why a caller mapping
   * codes to branches has to tell a missing one from an unknown one.
   */
  readonly code?: string
  /** The standard's own words for that code. */
  readonly condition?: string
  readonly severity?: 'success' | 'noData' | 'warning' | 'informational' | 'exception'
  readonly docUrl?: string
  /** Where in the statement, for a condition that happened somewhere. */
  readonly line?: number
  readonly column?: number
  readonly offset?: number
  /** The whole line `column` indexes into, for underlining it. */
  readonly excerpt?: string
}
